### ISSUE TITLE
Icon viewboxes center the icon vertically

### ISSUE THREAD

**Issue by westwood846** [glints-dev/glints-aries#212]
ORK 2.c

**Comment by rosslo** [comment]
After I studied the SVG's `viewport` and `viewbox`,  I realized we cannot use `viewbox` to center the icon vertically with a text, still need to use `css` instead.

Because almost all of the use cases of `Icon` need to be centered vertically, I planned to make `Icon` is centered vertically by default.

**Comment by rosslo** [comment]
PR: https://github.com/glints-dev/glints-aries/pull/255
